load("@rules_cc//cc:defs.bzl", "cc_library")

# TODO: Reference lidarlite_v3 from the submodule
cc_library(
    name = "lidarlite_v3",
    srcs = ["lidarlite_v3.cpp", "lidar.cpp"],
    hdrs = ["lidarlite_v3.hpp", "lidar.hpp"],
    visibility = ["//dodger:__pkg__"],
)
